### ISSUE TITLE
Discord Auth Error

### ISSUE THREAD

**Issue by skgupta507** [gneiru/kd#129]
Hey @gneiru  can u guide me to what the redirect URI must look like cause i tried some Redirect uris but they not seem to be doing the job. so i think iam doing something wrong here can u pls help me with the Redirect uri of discord.
ur help will be greatly appriciated.

**Comment by gneiru** [comment]
http://localhost:3005/api/auth/callback/discord

Try this @skgupta507 .

**Comment by gneiru** [comment]
Also add your url in Prod, with the same route. Just replace `http://localhost:3005` with the vercel url

**Comment by skgupta507** [comment]
hey @gneiru i tried the uri u provided.
after using it the auth screen worked but after authorization it is giving me this error _**To confirm your identity, sign in with the same account you used originally.**_ i have attached the screenshot of the same. i tried login again but it shows the same error. but if i use the google signin it works.
can u help with this.
![image](https://github.com/gneiru/kd/assets/131786207/b2422e85-cf73-4bdc-b070-401e332a8748)

**Comment by gneiru** [comment]
I think you're signing in with a discord account that has the same email address with some account you already signed up with Google.

**Comment by gneiru** [comment]
> hey @gneiru i tried the uri u provided. after using it the auth screen worked but after authorization it is giving me this error _**To confirm your identity, sign in with the same account you used originally.**_ i have attached the screenshot of the same. i tried login again but it shows the same error. but if i use the google signin it works. can u help with this. ![image](https://private-user-images.githubusercontent.com/131786207/331456309-b2422e85-cf73-4bdc-b070-401e332a8748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjUwNDQsIm5iZiI6MTcxNTkyNDc0NCwicGF0aCI6Ii8xMzE3ODYyMDcvMzMxNDU2MzA5LWIyNDIyZTg1LWNmNzMtNGJkYy1iMDcwLTQwMWUzMzJhODc0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNTQ1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDRkZTNhNjBiOGQ2YTA2MTkzMDIxNWYwN2JmYzk1YjNlZjlmMGRjNzFlOTJkMGQ3NDQyZWQwYTY1ZGFiYzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mXVhpoaRnPYPeOWo9iVLvo1UAJX5js1yu9JkigYgcJg)

I think you're signing in with a discord account that has the same email address with some account you already signed up with Google.

**Comment by skgupta507** [comment]
> I think you're signing in with a discord account that has the same email address with some account you already signed up with Google.

yes that is correct they  both have same email address.

**Comment by skgupta507** [comment]
so if both google and discord have same email id those users can only login through 1 method.

**Comment by gneiru** [comment]
Yes.

Please see https://next-auth.js.org/faq#security

**Comment by skgupta507** [comment]
> Yes.
> 
> Please see https://next-auth.js.org/faq#security

thanks for the help n clarification.
