### ISSUE TITLE
Hii i just downloaded this app but its full of ads cant download a single show..pls fix thix..and can u please make the downloaded shows available in the app itself instead of internal memory of phone phone pls? That would be great..thanks 😊

### ISSUE THREAD

**Issue by Aruraka** [gneiru/kd#29]

**Comment by gneiru** [comment]
Hello! Thank you for the feedback. I don’t think I can implement your request asap. We need the app to support offline mode first, so that it can download videos in the app itself.

**Comment by Aruraka** [comment]
Oh okay thanks for your response..I'm looking forward to ur update of this app..btw how long will it take to implement this feature?

**Comment by gneiru** [comment]
Hi @Aruraka, right now I still have no plans for that but PRs are always welcome
